In [81]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from collections import Counter
import math

In [ ]:
iris = load_iris()

In [ ]:
data = iris.data
target = iris.target
print(data.shape)
print(target.shape)
print(type(data))
print(type(target))

In [ ]:
y0_index = np.where(target==0)[0]
y1_index = np.where(target==1)[0]
y2_index = np.where(target==2)[0]
y0_index, y1_index, y2_index

In [ ]:
data_y0 = data[y0_index]
data_y1 = data[y1_index]
data_y2 = data[y2_index]
# data_y0, data_y0.shape

In [ ]:
P_y0 = float(len(y0_index))/ float(len(target))
P_y1 = float(len(y1_index))/ float(len(target))
P_y2 = float(len(y2_index))/ float(len(target))


In [ ]:
def mean(X):
    return (sum(X)/float(len(X)))



In [ ]:
n = len(set(float(t) for t in target))
m = data.shape[1]


pr = np.zeros(n)
mean = np.zeros((n,m))

for i in range(n):
    X_i = data[target==i]
    print(X_i.shape)
    mean[i] = np.mean(X_i, axis=0)

mean 

In [ ]:
# step

class NB_Guassian:
    def __init__(self):
        self.model = None
        self.class_priors = None    # 先验概率
        self.class_means = None     # 每个类别的特征均值
        self.class_vars = None      # 每个类别的特征方差
        self.n_classes = None       # 类别数量
        self.n_features = None      # 特征数量
    
    def fit(self, X, y):
        tmp_set = set(y)
        self.n_classes = len(tmp_set)
        self.n_features = X.shape[1]

        # 初始化参数
        self.class_priors = np.zeros(self.n_classes)
        self.class_means = np.zeros((self.n_classes, self.n_features))
        self.class_vars = np.zeros((self.n_classes, self.n_features))

        # 计算参数
        for i in range(self.n_classes):
            X_i = X[y==i]

            # 先验概率
            self.class_priors[i] = float(len(X_i))/ float(len(X))
            # 均值
            self.class_means[i] = np.mean(X_i, axis=0)
            # 方差
            self.class_vars[i] = np.var(X_i, axis=0, ddof=1)     # ddof 无偏估计
            self.class_vars[i] = np.maximum(self.class_vars[i], 1e-9)     # 不为0
        
        return self
    
    def predict(self, pre_data):     
        # 初始化
        log_probs = np.zeros((1, self.n_classes))

        # 计算
        for i in range(self.n_classes):
            # 似然概率
            log_likehood = -0.5 * np.sum(np.log(2*np.pi*self.class_vars[i]) + ( (pre_data - self.class_means[i])**2 / self.class_vars[i] ))
        
            log_probs[:,i] = np.log(self.class_priors[i]) + log_likehood
        
        return np.argmax(log_probs), log_probs

    def get_params(self):
        return {
            'class_priors': self.class_priors,
            'class_means': self.class_means,
            'class_vars': self.class_vars,
            'n_classes': self.n_classes,
            'n_features': self.n_features
        }

    def print_params(self):
        params = self.get_params()
        for key in params.keys():
            print(f"{key}:\n{params[key]}")    
        print("\n")


In [108]:
# step

iris = load_iris()
data, target = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(data, target ,test_size=0.2)

nbg = NB_Guassian()
nbg.fit(X_train, y_train)


sample_index = np.random.randint(0, len(X_test))
test_sample = X_test[sample_index]
true_label = y_test[sample_index]

pre_label, probs = nbg.predict(test_sample)

nbg.print_params()
print(f"预测概率(log)：{probs}")
print(f"预测结果：{pre_label}")
print(f"实际结果：{true_label}")


class_priors:
[0.33333333 0.34166667 0.325     ]
class_means:
[[5.03       3.425      1.46       0.2475    ]
 [5.9902439  2.78780488 4.28292683 1.34634146]
 [6.61282051 2.94358974 5.56410256 2.00769231]]
class_vars:
[[0.13548718 0.16192308 0.03528205 0.01178846]
 [0.28640244 0.09859756 0.24095122 0.04154878]
 [0.34535762 0.09041835 0.31973009 0.08020243]]
n_classes:
3
n_features:
4


预测概率(log)：[[-440.27002919  -15.3041106    -1.82548124]]
预测结果：2
实际结果：2
